### ISSUE TITLE
JWT Activity failed to resolve activity value: 'JavaWebTokenActivity'

### ISSUE THREAD

**Issue by rhopper-gwi** [ayh20/flogo-components#5]
I have imported the jwt activity into our instance of Tibco, and am using it in a Tibco Flow.  The Activity is Validating the token correctly and decoding the claims.  However, nothing can be done with the output.  Any attempt to map or log $activity[JavaWebTokenActivity] goes to the error handler.  I tested this with an unexpired JWT Token from a Salesforce Sandbox.  See attached log.
[jwt-sample-medium.log](https://github.com/ayh20/flogo-components/files/8045113/jwt-sample-medium.log)

**Comment by ayh20** [comment]
Hi, with my test suite i don't see any issues with the output or any errors using the results.
Can you confirm that your are using the latest version 0.1.5 ?
Can you share a test case flow so i can try to recreate locally ?  (You can send it to my TIBCO email address if you prefer ahampshire at tibco dot com)

**Comment by ayh20** [comment]
Just looking at your error again it looks like a mapping error...  Have you renamed the JWT activity step ? Changing the name and then not changing them downstream ... but the new mapper should handle that automatically ....

**Comment by rhopper-gwi** [comment]
I tested with this example, which was featured in the YouTube video:  https://github.com/alexandrev/flogo-jwt-sample-medium.git

**Comment by rhopper-gwi** [comment]
I did a pull from Git and re-uploaded the zip file for the jwt activity, to make sure I had the latest version (1.5).

It looks like the problem is only when I put the activity in a subflow.  I renamed the SubFlow to something more descriptive than "Start A SubFlow."  If  use the activity in the main flow, it works fine.

**Comment by ayh20** [comment]
I think Alex's flow was built on an old version of Flogo Enterprise and it doesn't work
[JWT Test.zip](https://github.com/ayh20/flogo-components/files/8050825/JWT.Test.zip)

In the attached file there is a tweaked version of the app that Alex has in his github .... and a test case (launch config) so that you can test it from the UI and see it work as a sub flow.
