### ISSUE TITLE
Please upgrade to Go 1.15 or greater

### ISSUE THREAD

**Issue by rhopper-gwi** [ayh20/flogo-components#7]
Today, I was researching a security alert and found this in the README of https://github.com/golang-jwt/jwt:  "Some older versions of Go have a security issue in the crypto/elliptic. Recommendation is to upgrade to at least 1.15 See issue dgrijalva/jwt-go#216 for more detail.  Our support of Go versions is aligned with Go's version release policy. So we will support a major version of Go until there are two newer major releases. We no longer support building jwt-go with unsupported Go versions, as these contain security vulnerabilities which will not be fixed."

**Comment by ayh20** [comment]
Done
